version: '3.8'

services:
  minecraft:
    image: itzg/minecraft-server:latest
    container_name: minecraft-server
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: "VANILLA"
      VERSION: "LATEST"
      MEMORY: "2G"
      WORLD: ${WORLD_NAME}
      LEVEL: ${WORLD_NAME}
      WHITELIST: ${WHITELIST}
      OPS: ${OPS}
      DIFFICULTY: ${DIFFICULTY:-normal}
      GAMEMODE: ${GAMEMODE:-survival}
      PVP: ${PVP:-true}
      MOTD: ${MOTD:-A Minecraft Server}
      SERVER_NAME: ${SERVER_NAME:-Minecraft Server}
      ENABLE_RCON: "true"
      RCON_PASSWORD: ${RCON_PASSWORD}
      RCON_PORT: 25575
      MAX_PLAYERS: ${MAX_PLAYERS:-20}
      VIEW_DISTANCE: ${VIEW_DISTANCE:-10}
      ALLOW_NETHER: ${ALLOW_NETHER:-true}
      ANNOUNCE_PLAYER_ACHIEVEMENTS: ${ANNOUNCE_PLAYER_ACHIEVEMENTS:-true}
      ENABLE_COMMAND_BLOCK: ${ENABLE_COMMAND_BLOCK:-false}
      FORCE_GAMEMODE: ${FORCE_GAMEMODE:-false}
      GENERATE_STRUCTURES: ${GENERATE_STRUCTURES:-true}
      HARDCORE: ${HARDCORE:-false}
      MAX_BUILD_HEIGHT: ${MAX_BUILD_HEIGHT:-256}
      MAX_WORLD_SIZE: ${MAX_WORLD_SIZE:-29999984}
      SPAWN_ANIMALS: ${SPAWN_ANIMALS:-true}
      SPAWN_MONSTERS: ${SPAWN_MONSTERS:-true}
      SPAWN_NPCS: ${SPAWN_NPCS:-true}
      ONLINE_MODE: ${ONLINE_MODE:-true}
    volumes:
      - ./worlds/${WORLD_NAME}:/data/world
      - ./server-data:/data
      - ./plugins:/plugins:ro
    restart: unless-stopped
    tty: true
    stdin_open: true
    
  backup:
    image: alpine:latest
    container_name: minecraft-backup
    depends_on:
      - minecraft
    environment:
      WORLD_NAME: ${WORLD_NAME}
    volumes:
      - ./worlds:/worlds
      - ./backups:/backups
      - ./scripts:/scripts:ro
    command: >
      sh -c "
        apk add --no-cache dcron &&
        echo '0 */48 * * * /scripts/backup.sh' > /var/spool/cron/crontabs/root &&
        crond -f -d 8
      "
    restart: unless-stopped